FROM ubuntu:18.04

# install dependencies
RUN apt update -y && apt install -y \
        python3 python3-dev python3-pip git

# copy docker-scripts directory to image
ADD ./docker-scripts/ /usr/share/docker-scripts/

# configure scripts as executables
RUN chmod 755 /usr/share/docker-scripts/*.sh

# make executables easy to find
RUN ln -s /usr/share/docker-scripts/*.sh /usr/bin/

# update pip to latest version
RUN pip3 install -U pip

ENTRYPOINT ["entrypoint.sh"]
