FROM ubuntu:18.04

# install dependencies
RUN apt update -y && apt install -y \
        python3 python3-dev python3-pip git

# configure default entrypoint command
ADD ./docker-scripts/entrypoint.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/entrypoint.sh

# update pip to latest version
RUN pip3 install -U pip

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
