version: "3.8"

services:      
  prod:
    build: ./ansible/
    working_dir: /ansible/
    volumes:
      - ./ansible/src:/ansible:Z,ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:Z,ro
    environment:
      ANSIBLE_INVENTORY: /inventory
  
  dev:
    build: ./ansible/
    working_dir: /ansible/
    command: ansible-playbook ./tests.yml
    volumes:
      - ./ansible/src:/ansible:Z,ro
    environment:
      ANSIBLE_INVENTORY: /inventory
