- name: Unify all tests into a single playbook
  hosts: ios

  # facts are not used in testing
  gather_facts: false

  tasks:
    - name: Define test vars
      set_fact:
        user:
          name: little-cisco
          # generate a new password every time, enforce a good password
          # policy even in development environment.
          password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits') }}"

    - include_tasks: ./tests/{{ item }}
      vars:
        test_user: "{{ user }}"
      with_items:
        - test-user-role.yml
        - test-banner-role.yml
        - test-config-role.yml
