- name: Unify all tests into a single playbook
  hosts: ios

  # facts are not used in testing
  gather_facts: false

  vars:
    registered_tests:
      - test-user-role.yml
      - test-banner-role.yml
      - test-config-role.yml

  tasks:
    - name: Define enhanced vars to test users
      set_fact:
        user:
          name: little-cisco
          # generate a new password every time, enforce a good password
          # policy even in development environment.
          password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits') }}"

    - name: Run tests carefully to always revert old configuration
      block:
        - include_tasks: ./tests/{{ item }}
          vars:
            test_user: "{{ user }}"
          with_items: "{{ registered_tests }}"

      always:
        - name: Ensure testing user is absent
          ios_user:
            name: "{{ user.name }}"
            state: absent
        
        - name: Ensure testing banners are absent
          ios_banner:
            banner: "{{ item }}"
            state: absent
          with_items:
            - motd
